services:
  # Servicio de API (Backend)
  api:
    image: img_bodegas_balam_api
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: bodegas_balam_api
    ports:
      - "9000:9000"
    env_file:
      - .env.dev  # Cargar variables de ambiente desde archivo (cp .env.example .env.dev)
    #depends_on:
    #  - db
    networks:
      - bodegas_network
    volumes:
      - ./app:/app/app

networks:
  bodegas_network:
    driver: bridge
    name: bodegas_network
    external: true
